name: Предложение
description: Предложить улучшение
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу нужно решить?
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Пример желаемого поведения
    validations:
      required: true
