"""Single source of truth for versions and release notes. Standard library only."""
import argparse
from datetime import date
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SEMVER = re.compile(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)")

def load_metadata(root=ROOT):
    data = json.loads((root / "version.json").read_text(encoding="utf-8"))
    if not SEMVER.fullmatch(data["version"]):
        raise ValueError("version must be MAJOR.MINOR.PATCH")
    if data["schema_version"] != 1 or not data["releases"]:
        raise ValueError("Unsupported schema or missing releases")
    if data["releases"][0]["version"] != data["version"]:
        raise ValueError("Latest release must match version")
    if data["releases"][0]["date"] != data["released"]:
        raise ValueError("Latest release date must match released")
    seen = set()
    previous = None
    for release in data["releases"]:
        value = release["version"]
        if not SEMVER.fullmatch(value) or value in seen:
            raise ValueError("Invalid or duplicate release version")
        number = tuple(map(int, value.split(".")))
        if previous is not None and number >= previous:
            raise ValueError("Releases must be in descending version order")
        previous = number
        seen.add(value)
        date.fromisoformat(release["date"])
        if not release["changes"]:
            raise ValueError("Release notes cannot be empty")
        for group, notes in release["changes"].items():
            if group not in {"Added", "Changed", "Fixed", "Removed", "Security"}:
                raise ValueError("Unknown changelog group: " + group)
            if not isinstance(notes, list) or not notes or not all(isinstance(n, str) and n.strip() for n in notes):
                raise ValueError("Notes must be a non-empty list of strings")
    return data

def release_notes(release):
    lines = [f"## [{release['version']}] — {release['date']}", "", release["title"], ""]
    for group, notes in release["changes"].items():
        lines.extend(["### " + group, ""])
        lines.extend("- " + note for note in notes)
        lines.append("")
    return "\n".join(lines)

def generated_files(data):
    version = data["version"]
    version_md = (
        "# Version\n\n"
        f"Current version: **{version}**\n\n"
        f"Release date: **{data['released']}**\n\n"
        f"Git tag: `v{version}`\n\n"
        "Source of truth: [version.json](version.json).\n"
        "This file is generated by `python tools/release.py --sync`.\n\n"
        "Use `python tools/release.py --bump patch --note \"Description\"` "
        "to prepare the next release. See [CONTRIBUTING.md](CONTRIBUTING.md).\n"
    )
    changelog = "# Changelog\n\nAll public releases. Generated from [version.json](version.json).\n\n"
    changelog += "\n".join(release_notes(r) for r in data["releases"])
    return {"VERSION.md": version_md, "CHANGELOG.md": changelog}

def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--sync", action="store_true")
    mode.add_argument("--bump", choices=["patch", "minor", "major"])
    parser.add_argument("--note", action="append", default=[])
    parser.add_argument("--date", default=date.today().isoformat())
    parser.add_argument("--tag", help="Also verify a release tag")
    args = parser.parse_args(argv)
    data = load_metadata()
    if args.bump:
        if not args.note or not all(n.strip() for n in args.note):
            parser.error("--bump requires at least one non-empty --note")
        date.fromisoformat(args.date)
        major, minor, patch = map(int, data["version"].split("."))
        if args.bump == "major":
            major, minor, patch = major + 1, 0, 0
        elif args.bump == "minor":
            minor, patch = minor + 1, 0
        else:
            patch += 1
        data["version"] = f"{major}.{minor}.{patch}"
        data["released"] = args.date
        data["releases"].insert(0, {
            "version": data["version"], "date": args.date,
            "title": "Release " + data["version"], "changes": {"Changed": args.note}
        })
        (ROOT / "version.json").write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.tag and args.tag != "v" + data["version"]:
        raise ValueError("Tag and version.json do not match")
    for name, expected in generated_files(data).items():
        path = ROOT / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                raise ValueError(name + " is out of sync; run --sync")
        else:
            path.write_text(expected, encoding="utf-8")
    print("Version metadata OK: " + data["version"])

if __name__ == "__main__":
    main()
